= Backend_Frontend_Kopplung

Die Webanwendung ist mit *Vue* aufgebaut, wobei Komponenten verwendet werden. Diese Komponenten sind in entsprechenden CARPET-Verzeichnis organisiert. Im Backend (ALADIN-Verzeichnis) werden die Komponenten in einer *JSON-Datei* definiert und deren Parameter initialisiert. In der JSON-Datei wird zudem die Reihenfolge der Komponenten auf der Seite festgelegt.

== Frontend (CARPET)

Unter *src/components* im CARPET-Verzeichnis sind verschiedene Vue-Komponenten implementiert, die mehrfach verwendet werden können.

=== Vue-Komponent definieren 

Nachdem Sie eine Vue-Datei erstellt haben, müssen Sie diese in der Datei *Canvas.vue* (src/components/Canvas.vue) importieren und im export default-Objekt registrieren, damit die Komponente global verwendet werden kann.

* Beispiel : 
....
// In Canvas.vue
import MyComponent from './components/MyComponent.vue';

export default {
  name: 'Canvas',
  components: {
    MyComponent
   }
};
....

== Backend (ALADIN)

Für die FermentExercise-Webanwendung ist im Backend die Datei *FermentExercise.json* zuständig. In dieser Datei werden die notwendigen APIs und Komponenten sowie deren Reihenfolge, Positionen und Parameter initialisiert und definiert.

Die *FermentExercise.json* ist also eine zentrale Konfigurationsdatei für die Webanwendung, die speziell für Fermentationsübungen (FermentExercises) gedacht ist. Sie ist strukturiert in verschiedene Abschnitte, um die Kommunikation mit der API, die Verarbeitung von Aufgaben im Worker-Bereich und die Darstellung der UI (Benutzeroberfläche) zu ermöglichen.

* Beispiel für FermentExercise.json:
....
{
  "API": [
    {
        "task": "FermentExercises",
        "name": "generateFermentationDataMain",
        "httpMethod": "post",
        "params": {
            "parameters": "object"
        }
	}
  ],
  "worker": {
    "FermentExercisesTask": {
      "minConsumers": 1,
      "consumerInstructions": {
        "generateFermentationDataMain": {
			"dependencies": ["generateFermentationDataMain"],
			"body": "async (taskDescription) => {let result = {};try { result = generateFermentationDataMain(taskDescription)} catch{} return result; }"
				}
      }
    }
  },
  "UI": {
    "currentTask": "FermentExercises",
    ...
    ...
    "components": {
      "2": {
        "type": "CheckboxGroup",
        "name": "Zu variierende Parameter",
        "isValid": true,
        "component": {
          "options": [
            "Zuluft",
            "BolusC",
            "Feed",
            "BolusN",
            "Drehzahl",
            "Druck",
            "Dauer"
          ],
          "jsonData": {}
        }
      }
    }
  }
}
....

=== Detaillierte Erklärung der Abschnitte
==== API :

* task: In welchem Task befinden (hier "FermentExercises").
* name: Der Name der Funktion, die in der API ausgeführt werden   soll (z.B. "generateFermentationDataMain"). 
    ** Alle nötige Funktionen müssen in eine *wrapperFunctionCallPython.ts* implementiert werden.

....
    export async function generateFermentationDataMain(parameter: any) {
	let check = editSaveParams(parameter);
	if (check) {
		let result = { foo: "bar" };
		try {
			let pythonScriptPath = "generateFermentationData.py";
			pythonScriptPath = path.join(__dirname, pythonScriptPath);
			(await runPythonScript(pythonScriptPath)) as any;

			result = JSON.parse(fs.readFileSync(path.join(__dirname, "data.json"), "utf-8"));
			const filePath = path.join(__dirname, "data.json");
			fs.writeFileSync(filePath, JSON.stringify(result, null, 2), "utf-8");
			
			//console.log(result);
			//insofern kryptsiche Zeichen in der JSON Ausgabe vorhanden sind .> Workaround mittels File
		} catch (error) {
			console.error("Error running Python script:", error);
		}
		return result;
	} else console.error("Die Daten aus Frontend konnten nicht in JSON-Datei gespeichert");
	return null;
}
....

    * Dann müsste diese Datei *wrapperFunctionCallPython.ts* in *TaskWrapper.ts* (./src/server/TaskWrapper.ts) importiert und in "generators" gesetzt werden :

....
    import { generateFermentationDataMain } from "../Tasks/Ferment/wrapperFunctionCallPython";
    import { generateFermentExercises } from "../Tasks/FermentExercises/wrapperFunctionCallPython";
    import { generateFermentationFeedBack } from "../Tasks/Ferment/wrapperFunctionCallPython"
    ...
    ...
    // TODO generalize generators into serialisable functions
    const generators: { [key: string]: any } = {
        GozintographTaskGenerator: GozintographTaskGenerator,
        ...
        generateFermentationDataMain: generateFermentationDataMain,
        generateFermentExercises: generateFermentExercises,
        generateFermentationFeedBack: generateFermentationFeedBack
    };
....

* httpMethod: Die HTTP-Methode, die für den API-Aufruf verwendet wird (z.B. POST).
* params: Hier können Parameter angegeben werden, die an die API übergeben werden. In diesem Fall handelt es sich um ein "parameters"-Objekt.

===== Worker :

* FermentExercisesTask: Der Worker-Abschnitt beschreibt, wie Aufgaben bearbeitet werden.
* minConsumers: Gibt an, wie viele "Consumer" (Verbraucher) erforderlich sind, um die Aufgabe zu verarbeiten.
* consumerInstructions: Hier wird beschrieben, wie die Aufgabe ausgeführt wird, mit einer generateFermentExercises-Funktion, die Asynchronität unterstützt.
* dependencies: Definiert, dass die generateFermentationDataMain-Funktion von sich selbst abhängt (dies könnte für spätere Erweiterungen oder Abhängigkeiten nützlich sein).

===== UI:

* currentTask: Gibt den aktuellen Task an, der im UI bearbeitet wird (hier "FermentExercises").
* components: In dem Abschnitt wird eine oder mehrere Vue-Komponenten definiert, die im Frontend implementiert sind. Hier werden sie aufgerufen und mit den nötigen Parametern initialisiert. Das bedeutet, dass man in diesem Abschnitt die UI-Komponenten definiert, die auf der Seite angezeigt werden sollen, und ihre spezifischen Parameter oder Daten, die von der Webanwendung benötigt werden.

** "2" : Der Schlüssel "2" dient dazu, diese spezielle Komponente zu identifizieren.
** "type" : hier wird definiert, welche Vue-Komponente aufgerufen wird.
** "name" : Der Name der Komponente wird hier definiert, in diesem Fall "Zu variierende Parameter". Das könnte der Titel oder die Bezeichnung der Checkbox-Gruppe sein, die im UI angezeigt wird.
** "component" : unter diesem Schlüssel werden die Paramater der Vue-Komponent (in diesem Fall CheckboxGroup.vue) initialisiert.







== Button im Frontend zur Übermittlung von Benutzereingaben an das Backend

=== Backendformular (in CARPET)
Das 'Backendformular' ist eine Vue-Datei, die im Backend als Typ (in FermentExcercise.json) verwendet wird.

Die *Backendformular.vue-Komponente* stellt ein dynamisches Formular zur Eingabe und Verarbeitung von Parametern bereit. Sie rendert verschiedene Formularelemente basierend auf ihrer formType-Eigenschaft und aktualisiert deren Werte über updateElement(). *Die Methode fetchData() erstellt ein payload-Objekt mit den aktuellen Eingaben und sendet es an das Backend*. Zusätzlich kann saveFetchData() die Startparameter aus einer JSON-Datei aktualisieren. Die Komponente nutzt computed, um Änderungen automatisch zu verfolgen, und ActionButtons, um verfügbare Aktionen zu steuern.

==== Die Funktion preparePayload
Die Funktion preparePayload sammelt alle Werte aus den Formularelementen und strukturiert sie in einem Objekt, das für den Backend-Aufruf benötigt wird. Dabei werden verschiedene Typen von Formularelementen berücksichtigt, wie Zahlenwerte, Bereiche oder Dropdowns. Falls zusätzliche Daten im System gespeichert sind, werden diese ebenfalls ergänzt. Schließlich wird das Objekt um die aktuelle Aufgabe (currentTask) und die gewünschte Aktion (instruction) erweitert.

....

const preparePayload = (instruction) => {
      const parameters: { [key: string]: any } = Object.entries(elements.value).reduce(
        (parameters, [name, parameter]: [string, { [key: string]: any }]) => {
          const { formType, initial } = parameter;
          let payload = { ...parameters, [name]: initial };
          if (formType === "RangeFormField") payload[name] = [initial.lowerValue, initial.upperValue];
          if (formType === "ValueFormField") payload[name] = parameter.value;
          const dataPfad = computed(() => `${path}__component__data`);
          if (dataPfad != null) {
            const data = computed(() => getProperty(`${path}__component__data`));
            Object.entries(data.value).forEach(([key, valuePath]) => {
              const value = getProperty(valuePath);
              payload[key] = value;
            });
          }

          return payload;
        },
        {}
      );
      const payload: { [key: string]: any } = { parameters };
      payload.type = currentTask.value;
      payload.task = currentTask.value;
      payload.instruction = instruction;

      return payload;
    };
....

==== Die Funktion fetchData
Die Funktion fetchData nutzt preparePayload, um die Nutzereingaben zu erfassen. Falls ein Speicherpfad für bereits abgerufene Daten existiert, werden die neuen Eingaben dort gesichert. Anschließend wird das fertige Payload-Objekt in der Konsole ausgegeben und über eine store.dispatch-Funktion an das Backend gesendet. Damit ermöglicht die Funktion die Kommunikation zwischen der Benutzeroberfläche und dem Backend, indem sie die Eingaben verarbeitet und weiterleitet.

....
const fetchData = (instruction) => {
      const payload = preparePayload(instruction);
      if(saveFetchedDataInTemplate_Path.value != null) saveFetchData(payload);
      console.log("Payload:", payload); // Ausgabe des Payloads in der Konsole
      store.dispatch("fetchTaskData", {
        payload: preparePayload(instruction),
        endpoint: `${currentTask.value}/${instruction}`
      });
    };
....

=== Backendformular in FermentExcercise.json benutzen

....
    "0": {
        "type": "BackendFormular",
        "name": "Diagramm generieren",
        "isValid": true,
        "component": {
            "actions": [
                {
                    "instruction": "generateFermentExercises",
                    "type": "fetchData",
                    "label": "Generieren!",
                    "dependsOn": [
                        "nodes__0__components__0__component__form__nodeAmount__isValid",
                        "nodes__0__components__0__component__form__seed__isValid",
                        "nodes__0__components__1__isValid"
                    ]
                }
            ],
            "form": {
                "nodeAmount": {
                    "isValid": true,
                    "formType": "DropdownFormField",
                    "label": "Organismus",
                    "type": "string",
                    "description": "Zur Verfügung stehende Organismus",
                    "action": { "instruction": "fetchTaskData", "type": "fetchData", "key": "schema" },
                    "initial": "S.cerevisiae",
                    "options": ["S.cerevisiae", "E.coli", "Testorganismus"],
                    "presets": {
                        "easy": "S.cerevisiae",
                        "medium": "E.coli",
                        "hard": "Testorganismus"
                    }
                },
                "seed": {
                    "formType": "ValueFormField",
                    "label": "Phasenanzahl",
                    "type": "String",
                    "description": "Setze einen beliebigen Wert für die Phasenanzahl",
                    "value": "3",
                    "boundaries": { "min": 0, "max": 20 },
                    "readOnly": false,
                    "validate": true,
                    "presets": {
                        "easy": "",
                        "medium": "",
                        "hard": ""
                    }
                }
                ...
                ...
            }
        }
    }
....


. Aktionen (actions) :
Das Formular enthält eine Schaltfläche "Generieren!", die eine Aktion ausführt:

** instruction: "generateFermentExercises" → Diese Funktion im Backend wird ausgeführt, wenn der Button gedrückt wird.
** type: "fetchData" → Es wird eine Anfrage an das Backend gesendet.
** dependsOn: Die Aktion wird nur aktiviert, wenn bestimmte Felder gültige Werte haben:
*** nodeAmount (Organismus)
*** seed (Phasenanzahl)
*** Ein weiteres Formularfeld (nodes__0__components__1__isValid)
. Formularfelder (form):

Das Formular kann aus beliebige Eingabefeldern bestehen.

Jeder Schlüssel im Abschnitt form entspricht einer Vue-Komponente, die aufgerufen wird, wobei ihre Parameter entsprechend den definierten Werten initialisiert werden.